version: "3.8"

services:
  api:
    build: .
    container_name: findmeai-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb+srv://kunduipsita61:Test123@cluster0.7g1xbj0.mongodb.net/find_me_ai
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads

  mongo:
    image: mongo:7
    container_name: findmeai-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"

volumes:
  mongo_data:
