"use client";

import { useEffect, useMemo, useState } from "react";

import AppNavbar from "@/components/AppNavbar";
import ProtectedRoute from "@/components/ProtectedRoute";
import AlertCard from "@/components/cards/AlertCard";
import PersonCard from "@/components/cards/PersonCard";
import LoadingSpinner from "@/components/ui/LoadingSpinner";
import Toast from "@/components/ui/Toast";
import { useAuth } from "@/context/AuthContext";
import {
  fetchAlerts,
  fetchFoundReports,
  fetchMissingReports,
} from "@/services/api";

export default function DashboardPage() {
  const { token } = useAuth();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [missingReports, setMissingReports] = useState<
    Awaited<ReturnType<typeof fetchMissingReports>>
  >([]);
  const [foundReports, setFoundReports] = useState<
    Awaited<ReturnType<typeof fetchFoundReports>>
  >([]);
  const [alerts, setAlerts] = useState<Awaited<ReturnType<typeof fetchAlerts>>>(
    [],
  );

  useEffect(() => {
    const loadData = async () => {
      if (!token) {
        setError("Authentication required. Please login again.");
        setLoading(false);
        return;
      }

      setLoading(true);
      setError("");
      try {
        const [missing, found, alertsData] = await Promise.all([
          fetchMissingReports(token),
          fetchFoundReports(token),
          fetchAlerts(token),
        ]);
        setMissingReports(missing);
        setFoundReports(found);
        setAlerts(alertsData);
      } catch (loadError) {
        const message =
          loadError instanceof Error
            ? loadError.message
            : "Failed to load dashboard data.";
        setError(message);
      } finally {
        setLoading(false);
      }
    };

    void loadData();
  }, [token]);

  const missingPersons = useMemo(
    () =>
      missingReports.map((item) => ({
        id: item._id,
        name: item.name || "Unknown",
        age: item.age ?? undefined,
        gender: (item.gender as "Male" | "Female" | "Other") ?? undefined,
        location: item.last_seen_location ?? undefined,
        description: item.additional_info || "No additional description.",
        imageUrl: `${process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000"}/${item.image_path.replace(/\\/g, "/")}`,
      })),
    [missingReports],
  );

  const foundPersons = useMemo(
    () =>
      foundReports.map((item) => ({
        id: item._id,
        name: "Found Person",
        location: item.found_location ?? undefined,
        description: item.additional_info || "No additional description.",
        imageUrl: `${process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8000"}/${item.image_path.replace(/\\/g, "/")}`,
        contact: item.contact_info ?? undefined,
      })),
    [foundReports],
  );

  const alertCards = useMemo(
    () =>
      alerts.map((item) => ({
        id: item._id,
        personImage:
          "https://images.unsplash.com/photo-1544717305-2782549b5136?w=500&q=80",
        confidence: Number((item.similarity * 100).toFixed(1)),
        location: "Match generated by AI pipeline",
        contactInfo: `Missing ID: ${item.missing_id} | Found ID: ${item.found_id}`,
      })),
    [alerts],
  );

  return (
    <div className="min-h-screen bg-slate-50">
      <AppNavbar />
      <ProtectedRoute requiredRole="user">
        <main className="mx-auto w-full max-w-7xl space-y-10 px-4 py-10 md:px-8">
          <section>
            <h1 className="text-3xl font-extrabold text-slate-900">
              Operations Dashboard
            </h1>
            <p className="mt-2 text-sm text-slate-600">
              Review active cases, found reports, and AI-generated match alerts.
            </p>
            {error ? (
              <div className="mt-4">
                <Toast message={error} tone="error" />
              </div>
            ) : null}
          </section>

          {loading ? (
            <div className="flex min-h-[30vh] items-center justify-center">
              <LoadingSpinner label="Loading dashboard..." />
            </div>
          ) : (
            <>
              <section>
                <div className="mb-4 flex items-center justify-between">
                  <h2 className="text-xl font-bold text-slate-900">
                    Missing Persons
                  </h2>
                  <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">
                    {missingPersons.length} records
                  </span>
                </div>
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                  {missingPersons.map((person) => (
                    <PersonCard key={person.id} person={person} />
                  ))}
                </div>
              </section>

              <section>
                <div className="mb-4 flex items-center justify-between">
                  <h2 className="text-xl font-bold text-slate-900">
                    Found Persons
                  </h2>
                  <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">
                    {foundPersons.length} records
                  </span>
                </div>
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3">
                  {foundPersons.map((person) => (
                    <PersonCard key={person.id} person={person} />
                  ))}
                </div>
              </section>

              <section>
                <div className="mb-4 flex items-center justify-between">
                  <h2 className="text-xl font-bold text-slate-900">Alerts</h2>
                  <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-700">
                    {alertCards.length} high-confidence matches
                  </span>
                </div>
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                  {alertCards.map((alert) => (
                    <AlertCard key={alert.id} alert={alert} />
                  ))}
                </div>
              </section>
            </>
          )}
        </main>
      </ProtectedRoute>
    </div>
  );
}
